##############################################
# 1. Paths
##############################################
path:
  data_path:          '/workspace/data/EmoV-DB'
  corpus_path:        '/workspace/montreal_forced_aligner/corpus'
  textgrid_path:      '/workspace/montreal_forced_aligner/aligned'
  preprocessed_path:  '/workspace/preprocessed'
  experiment_path:    '/workspace/experiments'


##############################################
# 2. Preprocessing
##############################################
preprocessing:
  noise_symbol:       ' [noise] '
  speakers:           ['bea', 'jenie', 'josh', 'sam']
  emotions:           ['neutral', 'amused', 'angry', 'disgusted', 'sleepy']
  sil_phones:         ['sil', 'spn', 'sp', '']
  pitch_averaging:    False
  energy_averaging:   False
  match_transcript:   False


##############################################
# 3. Audio (optimized for vocoder)
##############################################
audio:
  sampling_rate:      24000
  hop_length:         256
  win_length:         1024
  n_fft:              1024
  n_mels:             80
  f_min:              0.0
  f_max:              8000.0


##############################################
# 4. Training
##############################################
train:
  n_epohcs:           100
  max_iterations:     20000
  batch_size:         16
  learning_rate:      0.000001


##############################################
# 5. Model
##############################################
model:
  n_encoder_layers:   4
  n_heads:            2
  hidden_dim:         256
  kernel_size:        9
  dropout:            0.1
  alpha:              0.1
  beta:               1.0


##############################################
# 6. Miscellaneous
##############################################
misc:
  markers:             ['o', '^', 's', 'd']
  colors:             ['#7C00FE', '#F9E400', '#FFAF00', '#F5004F', '#00B2A9']


##############################################
# 7. Inference
##############################################
inference:
  mode:               'bucketize'     # 'bucketize' or 'inference'
  best_pth_path:      '/workspace/experiment/exp_5/best_model.pth'
  buckete_size:       3